[package]
name = "connl"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4.42"
rand = "0.9.2"
colored = "3.0.0"
terminal_size = "0.3"

[dependencies.uuid]
version = "1.18.1"
features = [
    "v4",
]
