[package]
name = "bindlocal-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4.42"

[dependencies.uuid]
version = "1.18.1"
features = [
    "v4",
]
